# Copyright Amazon.com, Inc. or its affiliates. All rights reserved.
# SPDX-License-Identifier: Apache-2.0
#
# Public variable surface for the BDA processor façade.
#
# This surface is intentionally preserved so the root `module.bda_processor`
# call still type-checks. Pattern-specific document processing is delegated to
# the shared engine (`module "engine"` -> ../unified-processor); most of these
# variables are forwarded straight through.

variable "name" {
  description = "Name for the BDA processor resources"
  type        = string
  default     = "bda-processor"
}

# Retained for root call compatibility. The former monolith used this bucket to
# stage CodeBuild Docker-image sources; the shared engine builds Lambdas from
# zip archives and no longer needs it. Kept so the root call type-checks.
variable "lambda_layers_bucket_arn" {
  description = "ARN of the S3 bucket for storing Lambda layers (retained for root-call compatibility; unused by the façade — the shared engine packages Lambdas from zip archives)."
  type        = string
  default     = ""
}

# API wiring
variable "enable_api" {
  description = "Whether the API is enabled. Use this instead of checking api_id != null to avoid unknown value issues in count."
  type        = bool
  default     = false
}

variable "api_id" {
  description = "ID of the GraphQL API that provides interfaces for querying document status and metadata"
  type        = string
  default     = null
}

variable "api_arn" {
  description = "ARN of the GraphQL API that provides interfaces for querying document status and metadata"
  type        = string
  default     = null
}

variable "api_graphql_url" {
  description = "GraphQL URL of the API that provides interfaces for querying document status and metadata"
  type        = string
  default     = null
}

# Shared environment ARNs
variable "input_bucket_arn" {
  description = "ARN of the S3 bucket where source documents to be processed are stored"
  type        = string
}

variable "output_bucket_arn" {
  description = "ARN of the S3 bucket where processed documents and extraction results are stored"
  type        = string
}

variable "working_bucket_arn" {
  description = "ARN of the S3 bucket used for storing intermediate processing artifacts"
  type        = string
}

variable "configuration_table_arn" {
  description = "ARN of the DynamoDB table that stores configuration settings"
  type        = string
}

variable "tracking_table_arn" {
  description = "ARN of the DynamoDB table that tracks document processing status and metadata"
  type        = string
}

variable "concurrency_table_arn" {
  description = "ARN of the DynamoDB table that manages concurrency limits for document processing"
  type        = string
}

# Processing environment configuration
variable "metric_namespace" {
  description = "The namespace for CloudWatch metrics emitted by the document processing system"
  type        = string
}

variable "log_level" {
  description = "The log level for document processing components"
  type        = string
}

variable "log_retention_days" {
  description = "The retention period for CloudWatch logs generated by document processing components"
  type        = number
  default     = 7
}

# Encryption
variable "enable_encryption" {
  description = "Whether encryption is enabled. Use this instead of checking encryption_key_arn != null to avoid unknown value issues in count."
  type        = bool
  default     = false
}

variable "encryption_key_arn" {
  description = "ARN of the KMS key used for encrypting resources in the document processing workflow"
  type        = string
  default     = null
}

# VPC configuration
variable "vpc_subnet_ids" {
  description = "List of subnet IDs for Lambda functions to run in"
  type        = list(string)
  default     = []
}

variable "vpc_security_group_ids" {
  description = "List of security group IDs for Lambda functions"
  type        = list(string)
  default     = []
}

# Layers
variable "idp_common_layer_arn" {
  description = "ARN of the IDP common Lambda layer containing shared utilities"
  type        = string
}

variable "base_layer_arn" {
  description = "ARN of the shared base Lambda layer (idp_common with docs_service extras, v0.4.11+)."
  type        = string
  default     = null
}

variable "evaluation_layer_arn" {
  description = "ARN of the dedicated evaluation Lambda layer (idp_common with evaluation extras). Forwarded to the engine; required by the engine when evaluation is enabled."
  type        = string
  default     = null
}

# BDA-specific (pattern-specific) input.
variable "data_automation_project_arn" {
  description = "The ARN of the Bedrock Data Automation Project used for document processing. Consumer-supplied; the project id is exposed as an output and the ARN is used to link configuration versions to the BDA branch via seeding (not a deploy-time engine input)."
  type        = string
}

# Evaluation configuration
variable "evaluation_baseline_bucket_name" {
  description = "Name of the S3 bucket containing baseline documents for evaluation. Leave empty to skip evaluation."
  type        = string
  default     = ""
}

variable "reporting_bucket_name" {
  description = "Name of the reporting bucket the evaluation function forwards accuracy results to. Leave null to disable the evaluation reporting fan-out."
  type        = string
  default     = null
}

variable "save_reporting_function_name" {
  description = "Name of the save_reporting_data Lambda the evaluation function invokes to persist accuracy results. Leave null to disable the evaluation reporting fan-out."
  type        = string
  default     = null
}

variable "save_reporting_function_arn" {
  description = "ARN of the save_reporting_data Lambda, used to scope the evaluation function's invoke grant."
  type        = string
  default     = null
}

# Summarization configuration
variable "enable_rule_validation" {
  description = "Enable rule validation Lambda functions for compliance assessment (v0.4.13+)"
  type        = bool
  default     = false
}

variable "summarization_guardrail" {
  description = "Optional Bedrock guardrail to apply to summarization model interactions"
  type = object({
    guardrail_id  = string
    guardrail_arn = string
  })
  default = null
}

variable "max_processing_concurrency" {
  description = "Maximum number of concurrent document processing tasks"
  type        = number
  default     = 100
}

# Document processing configuration
variable "config" {
  description = "Configuration values from config_library YAML files"
  type        = any
}

variable "lambda_tracing_mode" {
  description = "X-Ray tracing mode for Lambda functions. Valid values: Active, PassThrough"
  type        = string
  default     = "Active"
}

variable "tags" {
  description = "Tags to apply to resources"
  type        = map(string)
  default     = {}
}

variable "additional_configurations" {
  description = "Extra non-active, editable configuration versions seeded alongside the default (version_name => config object). Shown in the UI version dropdown."
  type        = any
  default     = {}
}

variable "seed_managed_configs" {
  description = "Seed the managed baseline configuration versions as non-active reference rows."
  type        = bool
  default     = true
}

variable "lambda_architecture" {
  description = "Target Lambda architecture (x86_64 | arm64), forwarded to the shared engine so function architectures match the idp_common layers."
  type        = string
  default     = "arm64"
  validation {
    condition     = contains(["x86_64", "arm64"], var.lambda_architecture)
    error_message = "lambda_architecture must be one of: x86_64, arm64."
  }
}

variable "enable_bda_ocr_backend" {
  description = "Provision the deployment-scoped Bedrock Data Automation OCR project required by the IDP v0.6 `ocr.backend: bda` configuration setting. Off by default: BDA is not available in every region, and an unconditional control-plane create would fail apply there. Forwarded to the unified-processor engine."
  type        = bool
  default     = false
}

variable "allowed_bedrock_model_ids" {
  description = "Bedrock model IDs every processing step is allowed to invoke, on top of the models resolved from the seeded configs. Set this for models operators will select in the UI later, which Terraform cannot see. Use [\"*\"] to allow any Bedrock model. Empty (default) grants only the resolved models."
  type        = list(string)
  default     = []
}
