# Copyright Amazon.com, Inc. or its affiliates. All rights reserved.
# SPDX-License-Identifier: Apache-2.0
#
# Variables for the SageMaker-UDOP processor façade (Pattern 3 retained).
#
# This is the public input surface. Pattern-specific fields (the consumer-
# supplied SageMaker endpoint) drive the engine's native SageMaker classification
# backend; all other fields are forwarded to the shared engine (`module.engine`).

variable "name" {
  description = "Name prefix for all resources"
  type        = string
}

# =============================================================================
# Pattern-specific: consumer-supplied SageMaker endpoint
# =============================================================================

variable "classification_endpoint_arn" {
  description = "ARN of the consumer-supplied SageMaker endpoint used for document classification. The façade provisions NO SageMaker hosting/training; it grants the classification Lambda sagemaker:InvokeEndpoint on this endpoint and passes its name as SAGEMAKER_ENDPOINT_NAME."
  type        = string
}

# =============================================================================
# Shared environment ARNs (forwarded to the engine)
# =============================================================================

variable "input_bucket_arn" {
  description = "ARN of the S3 bucket where source documents to be processed are stored"
  type        = string
  default     = null
}

variable "output_bucket_arn" {
  description = "ARN of the S3 bucket where processed documents and extraction results are stored"
  type        = string
  default     = null
}

variable "working_bucket_arn" {
  description = "ARN of the S3 bucket used for storing intermediate processing artifacts"
  type        = string
  default     = null
}

variable "configuration_table_arn" {
  description = "ARN of the DynamoDB table that stores configuration settings"
  type        = string
}

variable "tracking_table_arn" {
  description = "ARN of the DynamoDB table that tracks document processing status and metadata"
  type        = string
  default     = null
}

variable "concurrency_table_arn" {
  description = "ARN of the DynamoDB table that manages concurrency limits for document processing"
  type        = string
}

variable "api_graphql_url" {
  description = "GraphQL URL of the API that provides interfaces for querying document status and metadata"
  type        = string
  default     = null
}

variable "enable_api" {
  description = "Whether the API is enabled"
  type        = bool
  default     = false
}

variable "api_id" {
  description = "ID of the GraphQL API that provides interfaces for querying document status and metadata"
  type        = string
  default     = null
}

variable "api_arn" {
  description = "ARN of the GraphQL API that provides interfaces for querying document status and metadata"
  type        = string
  default     = null
}

variable "encryption_key_arn" {
  description = "ARN of the KMS key used for encrypting resources"
  type        = string
  default     = null
}

variable "metric_namespace" {
  description = "The namespace for CloudWatch metrics emitted by the document processing system"
  type        = string
  default     = null
}

variable "log_level" {
  description = "The log level for document processing components"
  type        = string
  default     = null
}

variable "log_retention_days" {
  description = "The retention period for CloudWatch logs generated by document processing components"
  type        = number
  default     = 7
}

variable "vpc_subnet_ids" {
  description = "List of subnet IDs for Lambda functions"
  type        = list(string)
  default     = []
}

variable "vpc_security_group_ids" {
  description = "List of security group IDs for Lambda functions"
  type        = list(string)
  default     = []
}

# =============================================================================
# Model configuration (forwarded to the engine)
# =============================================================================



variable "enable_rule_validation" {
  description = "Enable rule validation Lambda functions for compliance assessment (v0.4.13+)"
  type        = bool
  default     = false
}


variable "ocr_max_workers" {
  description = "Maximum number of concurrent workers for OCR processing"
  type        = number
  default     = 20
}

variable "classification_max_workers" {
  description = "Maximum number of concurrent workers for classification processing"
  type        = number
  default     = 20
}

variable "config" {
  description = "Document processing configuration (from config_library YAML), forwarded to the engine."
  type        = any
  default     = null
}

variable "idp_common_layer_arn" {
  description = "ARN of the IDP common layer"
  type        = string
}

variable "base_layer_arn" {
  description = "ARN of the shared base Lambda layer (v0.4.11+), forwarded to the engine."
  type        = string
  default     = null
}

variable "evaluation_layer_arn" {
  description = "ARN of the dedicated evaluation Lambda layer (idp_common with evaluation+docs_service extras). Required when evaluation is enabled."
  type        = string
  default     = null
}

variable "tags" {
  description = "Tags to apply to all resources"
  type        = map(string)
  default     = {}
}

variable "max_processing_concurrency" {
  description = "Maximum number of concurrent document processing tasks"
  type        = number
  default     = 100
}

variable "lambda_tracing_mode" {
  description = "X-Ray tracing mode for Lambda functions. Valid values: Active, PassThrough"
  type        = string
  default     = "Active"
}

variable "evaluation_baseline_bucket_name" {
  description = "Name of the S3 bucket containing baseline documents for evaluation. Leave empty to skip evaluation."
  type        = string
  default     = ""
}

variable "reporting_bucket_name" {
  description = "Name of the reporting bucket the evaluation function forwards accuracy results to. Leave null to disable the evaluation reporting fan-out."
  type        = string
  default     = null
}

variable "save_reporting_function_name" {
  description = "Name of the save_reporting_data Lambda the evaluation function invokes to persist accuracy results. Leave null to disable the evaluation reporting fan-out."
  type        = string
  default     = null
}

variable "save_reporting_function_arn" {
  description = "ARN of the save_reporting_data Lambda, used to scope the evaluation function's invoke grant."
  type        = string
  default     = null
}

variable "additional_configurations" {
  description = "Extra non-active, editable configuration versions seeded alongside the default (version_name => config object). Shown in the UI version dropdown."
  type        = any
  default     = {}
}

variable "bda_project_arn" {
  description = <<-EOT
    Optional BDA project ARN used as the fallback link for use_bda:true
    additional versions that omit their own per-version `bda_project_arn`. Does
    not relink the `default` version (stays pipeline). A per-version
    `bda_project_arn` takes precedence. Does not gate the BDA branch — both
    branches are always deployed and route at runtime by the config's use_bda.
  EOT
  type        = string
  default     = null
}

variable "seed_managed_configs" {
  description = "Seed the managed baseline configuration versions as non-active reference rows."
  type        = bool
  default     = true
}

variable "lambda_architecture" {
  description = "Target Lambda architecture (x86_64 | arm64), forwarded to the shared engine so function architectures match the idp_common layers."
  type        = string
  default     = "arm64"
  validation {
    condition     = contains(["x86_64", "arm64"], var.lambda_architecture)
    error_message = "lambda_architecture must be one of: x86_64, arm64."
  }
}

variable "enable_bda_ocr_backend" {
  description = "Provision the deployment-scoped Bedrock Data Automation OCR project required by the IDP v0.6 `ocr.backend: bda` configuration setting. Off by default: BDA is not available in every region, and an unconditional control-plane create would fail apply there. Forwarded to the unified-processor engine."
  type        = bool
  default     = false
}

variable "allowed_bedrock_model_ids" {
  description = "Bedrock model IDs every processing step is allowed to invoke, on top of the models resolved from the seeded configs. Set this for models operators will select in the UI later, which Terraform cannot see. Use [\"*\"] to allow any Bedrock model. Empty (default) grants only the resolved models."
  type        = list(string)
  default     = []
}
