# Copyright Amazon.com, Inc. or its affiliates. All rights reserved.
# SPDX-License-Identifier: Apache-2.0
variable "name" {
  description = "Name for the Bedrock LLM processor resources"
  type        = string
  default     = "bedrock-llm-processor"
}

# Flat variables for processing environment resources - ARNs only
variable "enable_api" {
  description = "Whether the API is enabled"
  type        = bool
  default     = false
}

variable "api_id" {
  description = "ID of the GraphQL API that provides interfaces for querying document status and metadata"
  type        = string
  default     = null
}

variable "api_arn" {
  description = "ARN of the GraphQL API that provides interfaces for querying document status and metadata"
  type        = string
  default     = null
}

variable "api_graphql_url" {
  description = "GraphQL URL of the API that provides interfaces for querying document status and metadata"
  type        = string
  default     = null
}

variable "input_bucket_arn" {
  description = "ARN of the S3 bucket where source documents to be processed are stored"
  type        = string
}

variable "output_bucket_arn" {
  description = "ARN of the S3 bucket where processed documents and extraction results are stored"
  type        = string
}

variable "working_bucket_arn" {
  description = "ARN of the S3 bucket used for temporary processing files"
  type        = string
}

variable "configuration_table_arn" {
  description = "ARN of the DynamoDB table that stores configuration settings"
  type        = string
}

variable "tracking_table_arn" {
  description = "ARN of the DynamoDB table that tracks document processing status and metadata"
  type        = string
}

variable "concurrency_table_arn" {
  description = "ARN of the DynamoDB table that manages concurrency limits for document processing"
  type        = string
}

variable "metric_namespace" {
  description = "The namespace for CloudWatch metrics emitted by the document processing system"
  type        = string
}

variable "log_level" {
  description = "The log level for document processing components"
  type        = string
}

variable "encryption_key_arn" {
  description = "ARN of the KMS key used for encrypting resources"
  type        = string
  default     = null
}

variable "enable_encryption" {
  description = "Whether encryption is enabled. Use this instead of checking encryption_key_arn != null to avoid unknown value issues in for_each/count."
  type        = bool
  default     = false
}

variable "log_retention_days" {
  description = "The retention period for CloudWatch logs generated by document processing components"
  type        = number
  default     = 7
}

variable "vpc_subnet_ids" {
  description = "List of subnet IDs for VPC configuration"
  type        = list(string)
  default     = []
}

variable "vpc_security_group_ids" {
  description = "List of security group IDs for VPC configuration"
  type        = list(string)
  default     = []
}



variable "idp_common_layer_arn" {
  description = "ARN of the IDP common Lambda layer containing shared utilities"
  type        = string
}

variable "base_layer_arn" {
  description = "ARN of the shared base Lambda layer (idp_common with docs_service extras, v0.4.11+)"
  type        = string
  default     = null
}

variable "evaluation_layer_arn" {
  description = "ARN of the dedicated evaluation Lambda layer (idp_common with evaluation+docs_service extras, includes munkres/numpy). Required when evaluation_enabled=true."
  type        = string
  default     = null
}

variable "enable_rule_validation" {
  description = "Enable rule validation Lambda functions for compliance assessment (v0.4.13+)"
  type        = bool
  default     = false
}

# =============================================================================
# LAMBDA HOOK INFERENCE VARIABLES (v0.4.15+)
# =============================================================================
# These variables pre-grant Step Functions InvokeFunction permissions for custom
# Lambda hooks. The actual hook ARNs are stored in the DynamoDB configuration
# table (model_lambda_hook_arn field) and referenced when model_id = "LambdaHook".
# Function names must start with "GENAIIDP-" per the naming convention.

variable "lambda_hook_ocr" {
  description = "ARN or name of custom Lambda for OCR step hook inference. Must start with 'GENAIIDP-'. (v0.4.15+)"
  type        = string
  default     = ""
  validation {
    condition     = var.lambda_hook_ocr == "" || startswith(var.lambda_hook_ocr, "GENAIIDP-")
    error_message = "lambda_hook_ocr must be empty or start with 'GENAIIDP-'."
  }
}

variable "lambda_hook_classification" {
  description = "ARN or name of custom Lambda for Classification step hook inference. Must start with 'GENAIIDP-'. (v0.4.15+)"
  type        = string
  default     = ""
  validation {
    condition     = var.lambda_hook_classification == "" || startswith(var.lambda_hook_classification, "GENAIIDP-")
    error_message = "lambda_hook_classification must be empty or start with 'GENAIIDP-'."
  }
}

variable "lambda_hook_extraction" {
  description = "ARN or name of custom Lambda for Extraction step hook inference. Must start with 'GENAIIDP-'. (v0.4.15+)"
  type        = string
  default     = ""
  validation {
    condition     = var.lambda_hook_extraction == "" || startswith(var.lambda_hook_extraction, "GENAIIDP-")
    error_message = "lambda_hook_extraction must be empty or start with 'GENAIIDP-'."
  }
}

variable "lambda_hook_assessment" {
  description = "ARN or name of custom Lambda for Assessment step hook inference. Must start with 'GENAIIDP-'. (v0.4.15+)"
  type        = string
  default     = ""
  validation {
    condition     = var.lambda_hook_assessment == "" || startswith(var.lambda_hook_assessment, "GENAIIDP-")
    error_message = "lambda_hook_assessment must be empty or start with 'GENAIIDP-'."
  }
}

variable "lambda_hook_summarization" {
  description = "ARN or name of custom Lambda for Summarization step hook inference. Must start with 'GENAIIDP-'. (v0.4.15+)"
  type        = string
  default     = ""
  validation {
    condition     = var.lambda_hook_summarization == "" || startswith(var.lambda_hook_summarization, "GENAIIDP-")
    error_message = "lambda_hook_summarization must be empty or start with 'GENAIIDP-'."
  }
}

variable "classification_max_workers" {
  description = "The maximum number of concurrent workers for document classification"
  type        = number
  default     = 20
}

variable "max_pages_for_classification" {
  description = "Maximum number of pages to use for classification. Set to 'ALL' to use all pages, or a numeric value to limit."
  type        = string
  default     = "ALL"

  validation {
    condition     = var.max_pages_for_classification == "ALL" || can(tonumber(var.max_pages_for_classification))
    error_message = "max_pages_for_classification must be 'ALL' or a numeric value."
  }
}

variable "classification_guardrail" {
  description = "Optional Bedrock guardrail to apply to classification model interactions"
  type = object({
    guardrail_id  = string
    guardrail_arn = string
  })
  default = null
}

variable "extraction_guardrail" {
  description = "Optional Bedrock guardrail to apply to extraction model interactions"
  type = object({
    guardrail_id  = string
    guardrail_arn = string
  })
  default = null
}

variable "ocr_max_workers" {
  description = "The maximum number of concurrent workers for OCR processing"
  type        = number
  default     = 20
}

variable "evaluation_enabled" {
  description = "Controls whether extraction results are evaluated for accuracy"
  type        = bool
  default     = false
}

variable "evaluation_baseline_bucket_arn" {
  description = "ARN of the S3 bucket containing baseline documents for evaluation. Required when evaluation_enabled is true."
  type        = string
  default     = null
}

variable "reporting_bucket_name" {
  description = "Name of the reporting bucket the evaluation function forwards accuracy results to. Leave null to disable the evaluation reporting fan-out."
  type        = string
  default     = null
}

variable "save_reporting_function_name" {
  description = "Name of the save_reporting_data Lambda the evaluation function invokes to persist accuracy results. Leave null to disable the evaluation reporting fan-out."
  type        = string
  default     = null
}

variable "save_reporting_function_arn" {
  description = "ARN of the save_reporting_data Lambda, used to scope the evaluation function's invoke grant."
  type        = string
  default     = null
}

variable "is_summarization_enabled" {
  description = "Controls whether document summarization is enabled"
  type        = bool
  default     = false
}

variable "summarization_guardrail" {
  description = "Optional Bedrock guardrail to apply to summarization model interactions"
  type = object({
    guardrail_id  = string
    guardrail_arn = string
  })
  default = null
}

variable "max_processing_concurrency" {
  description = "Maximum number of concurrent document processing tasks"
  type        = number
  default     = 100
}

variable "config" {
  description = "Optional configuration values to override defaults from config.yaml"
  type        = any
  default     = null
}



variable "enable_hitl" {
  description = "Whether to enable Human-in-the-Loop (HITL) functionality for document review"
  type        = bool
  default     = false
}

variable "assessment_guardrail" {
  description = "Optional Bedrock guardrail configuration for assessment model interactions"
  type = object({
    guardrail_id      = string
    guardrail_version = string
  })
  default = null
}

variable "section_splitting_strategy" {
  description = "Strategy for splitting documents into sections before extraction. Valid values: disabled, page, llm_determined"
  type        = string
  default     = "disabled"

  validation {
    condition     = contains(["disabled", "page", "llm_determined"], var.section_splitting_strategy)
    error_message = "section_splitting_strategy must be one of: disabled, page, llm_determined."
  }
}

variable "enable_agentic_extraction" {
  description = "Whether to enable agentic extraction using Strands agent framework"
  type        = bool
  default     = false
}

variable "review_agent_model" {
  description = "Bedrock model ID for the review agent. If empty, uses the extraction model."
  type        = string
  default     = ""
}

variable "lambda_tracing_mode" {
  description = "X-Ray tracing mode for Lambda functions. Valid values: Active, PassThrough"
  type        = string
  default     = "Active"
}

variable "tags" {
  description = "A map of tags to add to all resources"
  type        = map(string)
  default     = {}
}

variable "additional_configurations" {
  description = "Extra non-active, editable configuration versions seeded alongside the default (version_name => config object). Shown in the UI version dropdown."
  type        = any
  default     = {}
}

variable "bda_project_arn" {
  description = <<-EOT
    Optional BDA project ARN used as the fallback link for use_bda:true
    additional versions that omit their own per-version `bda_project_arn`. Does
    not relink the `default` version (stays pipeline). A per-version
    `bda_project_arn` takes precedence. Does not gate the BDA branch — both
    branches are always deployed and route at runtime by the config's use_bda.
  EOT
  type        = string
  default     = null
}

variable "seed_managed_configs" {
  description = "Seed the managed baseline configuration versions as non-active reference rows."
  type        = bool
  default     = true
}

variable "lambda_architecture" {
  description = "Target Lambda architecture (x86_64 | arm64), forwarded to the shared engine so function architectures match the idp_common layers."
  type        = string
  default     = "arm64"
  validation {
    condition     = contains(["x86_64", "arm64"], var.lambda_architecture)
    error_message = "lambda_architecture must be one of: x86_64, arm64."
  }
}

variable "enable_bda_ocr_backend" {
  description = "Provision the deployment-scoped Bedrock Data Automation OCR project required by the IDP v0.6 `ocr.backend: bda` configuration setting. Off by default: BDA is not available in every region, and an unconditional control-plane create would fail apply there. Forwarded to the unified-processor engine."
  type        = bool
  default     = false
}

variable "allowed_bedrock_model_ids" {
  description = "Bedrock model IDs every processing step is allowed to invoke, on top of the models resolved from the seeded configs. Set this for models operators will select in the UI later, which Terraform cannot see. Use [\"*\"] to allow any Bedrock model. Empty (default) grants only the resolved models."
  type        = list(string)
  default     = []
}
